<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>neural.net - Admin Page</title>
    <#include "style.ftlh">
</head>
<body>
    <#include "header.ftlh">
    <div class="container">
        <h1>Администратор</h1>
        <ul>
            <li><a href="/admin/manage-hashtags">Управление хештегами</a></li>
            <li><a href="/admin/manage-users">Управление пользователями</a></li>
        </ul>
    </div>

</body>
</html>