<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>neural.net - Course Coursename</title>
    <#include "style.ftlh">
</head>
<body>
    <#include "header.ftlh">
    <div class="container" style="line-height: 1.5">
        <h1>Курс "Разработка клиент-серверных приложений"</h1>
        <p>от РТУ МИРЭА</p>

        В рамках курса вы получите следующие умения: (если там будет список)
        <ul>
            <li>Работа с Java Servlet</li>
            <li>Веб-клиент на JS, PHP</li>
            <li>Фреймворк Java Spring</li>
        </ul>
    </div>


</body>
</html>