<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>neural.net - Feed</title>
    <#include "style.ftlh">
</head>
<body>
    <#include "header.ftlh">
    <section>
        <div class="container">
            <h1>Подписки</h1>
            <!--subcsribers list-->
        </div>
    </section>
</body>
</html>