<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>neural.net - Free Education</title>
    <#include "style.ftlh">
</head>
<body>
    <#include "header.ftlh">

    <section id="about">
        <div class="container">
            <div class="about__inner">
                <div>
                    <div class="about__title">
                        <h1>СВОБОДНАЯ ОБРАЗОВАТЕЛЬНАЯ ПЛАТФОРМА</h1><br>
                        Откройтесь для новых знаний и измените свою жизнь прямо сейчас!
                    </div>

                    <div class="about__descr">
                        Вступите в открытое международное сообщество преподавателей, авторов,  менторов и просто профессионалов.
                    </div>
                </div>

                <div id="join"><a href="/signup">Присоединиться</a></div>
            </div>
        </div>
    </section>

    <section id="benefits">
        <div class="container">
            <div class="benefits__inner">
                <div class="benefit">
                    <div class="benefit__name">
                        <img src="./img/article_icon.png" alt="">
                        <p>Статьи</p>
                    </div>
                    <div class="benefit__descr">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex rerum consectetur, aspernatur dolore optio, dolor mollitia temporibus ad repellat perspiciatis obcaecati eaque qui similique nemo voluptas magnam. Ex, magni. Id.
                    </div>
                </div>

                <div class="benefit">
                    <div class="benefit__name">
                        <img src="./img/logo_icon.png" alt="">
                        <p>Преподаватели</p>
                    </div>
                    <div class="benefit__descr">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex rerum consectetur, aspernatur dolore optio, dolor mollitia temporibus ad repellat perspiciatis obcaecati eaque qui similique nemo voluptas magnam. Ex, magni. Id.
                    </div>
                </div>

                <div class="benefit">
                    <div class="benefit__name">
                        <img src="./img/org_icon.png" alt="">
                        <p>Образовательные организации</p>
                    </div>
                    <div class="benefit__descr">
                        Получите сертификат или даже ученую степень ведущих образовательных организаций, не выходя из дома.
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>